using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace AppFacturacion2018
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private List<string> Datos() {
            List<string> listDatos = new List<string>();
            listDatos.Add("Aarón (excelso), I-VII								");
            listDatos.Add("Abdón (siervo de Dios), 30-VII                       ");
            listDatos.Add("Abel (ídolo), 28-XII                                 ");
            listDatos.Add("Abelardo (muy noble), 28-XII                         ");
            listDatos.Add("Abrahán (padre de muchedumbres), 9-X                 ");
            listDatos.Add("Absalón (mi Padre, Dios, es bienestar), 2-III        ");
            listDatos.Add("Acacio (sin malicia), 9-IV                           ");
            listDatos.Add("Adalberto (brillante por su nobleza), 15-II          ");
            listDatos.Add("Adán (hecho de tierra), 29-VII                       ");
            listDatos.Add("Adela (noble), 8-IX                                  ");
            listDatos.Add("Adelaida (de linaje noble), 5-II                     ");
            listDatos.Add("Adolfo (lobo noble), 27-IX                           ");
            listDatos.Add("Adón (señor), 16-XII                                 ");
            listDatos.Add("Adrián (de la ciudad de Adria), 8-VII                ");
            listDatos.Add("Agueda (buena), 5-II                                 ");
            listDatos.Add("Agustín (=Augusto), 28-VIII                          ");
            listDatos.Add("Alberto (brillante por su nobleza), 15-XI            ");
            listDatos.Add("Albina (blanca), 16-XII                              ");
            listDatos.Add("Alejandro (defensor de los hombres), 3-V             ");
            listDatos.Add("Alejo (que repele el mal), 17-VII                    ");
            listDatos.Add("Alfonso (dispuesto al combate), I-VIII               ");
            listDatos.Add("Alfredo (amigo de los elfos o dioses), 17-I          ");
            listDatos.Add("Alicia (noble), 23-VI                                ");
            listDatos.Add("Alipio (sin pena), 15-VIII                           ");
            listDatos.Add("Almudena (granero), 9-XI                             ");
            listDatos.Add("Alvaro (vigilante), 19-II                            ");
            listDatos.Add("Amadeo (que ama a Dios), 30-IV                       ");
            listDatos.Add("Amaro (de gran riqueza), 25-I                        ");
            listDatos.Add("Ambrosio (inmortal), 7-XII                           ");
            listDatos.Add("Amelia o Amalia (enérgica), 31-V                     ");
            listDatos.Add("Ana (gracia de Dios), 26-VII                         ");
            listDatos.Add("Ananías (gracia del Señor), I-XII                    ");
            listDatos.Add("Anastasia (resucitada), 28-X                         ");
            listDatos.Add("Anatolio (oriental), 20-XI                           ");
            listDatos.Add("Andrés (varonil), 30-XI                              ");
            listDatos.Add("Ángel (enviado), 2-X                                 ");
            listDatos.Add("Anselmo (que tiene la protección divina), 21-IV      ");
            listDatos.Add("Antero (florido), 3-I                                ");
            listDatos.Add("Antonio (floreciente), 13-VI                         ");
            listDatos.Add("Aquiles (sin labio), 7-XI                            ");
            listDatos.Add("Araceli (altar del cielo), 2-V                       ");
            listDatos.Add("Aránzazu (espino), 9-IX                              ");
            listDatos.Add("Arcadio (de Arcadia, venturoso), 4-III               ");
            listDatos.Add("Aresio (de Ares, dios de la guerra), 10-VI           ");
            listDatos.Add("Ariadna (o Aridna, dulce cantante), 17-IX            ");
            listDatos.Add("Aristides (hijo del mejor), 31-VIII                  ");
            listDatos.Add("Arnaldo (luchador como un águila), 10-II             ");
            listDatos.Add("Artemio (incolúmne), 6-VI                            ");
            listDatos.Add("Arturo (oso noble), I-IX                             ");
            listDatos.Add("Atanasio (inmortal), 2-V                             ");
            listDatos.Add("Augusto (magnifico), 7-V                             ");
            listDatos.Add("Áurea (dorada), 19-VII                               ");
            listDatos.Add("Aurelia (dorada), 25-X                               ");
            listDatos.Add("Aureliano (dorado), 16-VI                            ");
            listDatos.Add("Aurelio (dorado), 27-VII                             ");
            listDatos.Add("Baldomero (luchador famoso), 27-II                   ");
            listDatos.Add("Balduino (amigo valiente), 26-VIII                   ");
            listDatos.Add("Baltasar (protegido de Baal), 6-I                    ");
            listDatos.Add("Bárbara (extranjera), 4-XII                          ");
            listDatos.Add("Bartolomé (hijo de labrador), 24-VIII                ");
            listDatos.Add("Basileo (regio), 26-IV                               ");
            listDatos.Add("Beatriz (que hace feliz), 18-I                       ");
            listDatos.Add("Belén (casa de pan), 25-XII                          ");
            listDatos.Add("Beltrán (cuervo brillante), 1-VIII                   ");
            listDatos.Add("Benedicto (bendito), 7-V                             ");
            listDatos.Add("Benigno (bueno, amable), 28-VI                       ");
            listDatos.Add("Benjamín (hijo de dicha), 31-III                     ");
            listDatos.Add("Bernabé (gemelo), 11-VI                              ");
            listDatos.Add("Bernardo (oso fuerte), 14-IV                         ");
            listDatos.Add("Blanca (brillante, distinguida), 5-VIII              ");
            listDatos.Add("Blas (tartamudo), 3-II                               ");
            listDatos.Add("Bonifacio (bienhechor), 8-V                          ");
            listDatos.Add("Bruno (moreno), 6-X                                  ");
            listDatos.Add("Calixto (bellísimo), 14-X                            ");
            listDatos.Add("Camilo (que prepara el sacrificio), 14-VII           ");
            listDatos.Add("Cándida (blanca), 29-VIII                            ");
            listDatos.Add("Carina (querida), 7-XI                               ");
            listDatos.Add("Carlos (hombre fuerte), 4-XI                         ");
            listDatos.Add("Carmen (viña), 16-VII                                ");
            listDatos.Add("Casiano (de Casio), 26-III                           ");
            listDatos.Add("Casimiro (que enseña la paz), 4-III                  ");
            listDatos.Add("Casio (cazador con red),                             ");
            listDatos.Add("Catalina (pura), 29-IV                               ");
            listDatos.Add("Cayetano (de Gaeta), 7-VIII                          ");
            listDatos.Add("Cayo (alegría de padres), 4-I                        ");
            listDatos.Add("Cecilia (ciega), 22-XI                               ");
            listDatos.Add("Ceferino (como el céfiro), 26-VIII                   ");
            listDatos.Add("Celia (celestial), 21-X                              ");
            listDatos.Add("Celso (excelso), 1-IV                                ");
            listDatos.Add("Cesáreo (el que nace abierta la madre), 27-VIII      ");
            listDatos.Add("Cipriano (de Chipre), 12-X                           ");
            listDatos.Add("Cirilo (señorial), 27-VI                             ");
            listDatos.Add("Cirino (señorial), 12-VI                             ");
            listDatos.Add("Ciro (sol), 14-VII                                   ");
            listDatos.Add("Claudio (cojo), 26-IV                                ");
            listDatos.Add("Cleofás (esclarecido por su gloria), 25-IX           ");
            listDatos.Add("Clotilde (que lucha con gloria), 3-VI                ");
            listDatos.Add("Colombo (paloma), 13-IX                              ");
            listDatos.Add("Columba (paloma), 17-IX                              ");
            listDatos.Add("Columbano (como paloma), 17-IX                       ");
            listDatos.Add("Conrado (de consejo atrevido), 22-III                ");
            listDatos.Add("Constancio (constante), 26-VIII                      ");
            listDatos.Add("Constantino (firme), 27-VII                          ");
            listDatos.Add("Cosme (adornado), 26-IX                              ");
            listDatos.Add("Cristina (cristiana), 15-XII                         ");
            listDatos.Add("Cristóbal (que lleva a Cristo), 10-VII               ");
            listDatos.Add("Daciano (de Dacia), 4-VI                             ");
            listDatos.Add("Dacio (de Dacia), 14-I                               ");
            listDatos.Add("Dámaso (domador), 11-XII                             ");
            listDatos.Add("Damián (hombre de pueblo), 26-IX                     ");
            listDatos.Add("Daniel (Dios es mi juez), 21-VII                     ");
            listDatos.Add("Dario (protector), 19-XII                            ");
            listDatos.Add("David (amado), 29-XII                                ");
            listDatos.Add("Demócrito (juez del pueblo), 31-VII                  ");
            listDatos.Add("Diego (= Santiago), 13-XI                            ");
            listDatos.Add("Dimas (moribundo), 10-V                              ");
            listDatos.Add("Domingo (el día del Señor), 8-VIII                   ");
            listDatos.Add("Donato (donado), 9-II                                ");
            listDatos.Add("Dorotea (don de Dios), 6-II                          ");
            listDatos.Add("Edmundo (que defiende sus bienes), 16-XI             ");
            listDatos.Add("Eduardo (fuerte por su riqueza), 18-III              ");
            listDatos.Add("Eduvigis (luchadora), 16-X                           ");
            listDatos.Add("Efrén (fructífero), 9-VI                             ");
            listDatos.Add("Elena (luna), 18-VIII                                ");
            listDatos.Add("Elías (mi Dios es Yahvé), 27-II                      ");
            listDatos.Add("Elisa (que jura por Dios), 5-XII                     ");
            listDatos.Add("Eliseo (Dios es salvación), 14-VI                    ");
            listDatos.Add("Emiliano ( = Emilio), 29-IV                          ");
            listDatos.Add("Emilio (amable), 22-V                                ");
            listDatos.Add("Enrique (rico en fincas), 13-VII                     ");
            listDatos.Add("Epifanía (manifestación), 6-I                        ");
            listDatos.Add("Erico (que merece honor), 18-V                       ");
            listDatos.Add("Ernesto (potencia de águila), 7-XI                   ");
            listDatos.Add("Esdras (Dios ayuda), 13-VII                          ");
            listDatos.Add("Esiquio (alma buena), 26-XI                          ");
            listDatos.Add("Esteban (corona), 26-XII                             ");
            listDatos.Add("Ester (estrella), 24-V                               ");
            listDatos.Add("Eugenia (bien nacida), 25-XII                        ");
            listDatos.Add("Eulalia (que habla bien), 12-II                      ");
            listDatos.Add("Eusebio (piadoso), 21-VI                             ");
            listDatos.Add("Eva (mujer), 19-XII                                  ");
            listDatos.Add("Evaristo (muy agradable), 26-X                       ");
            listDatos.Add("Ezequiel (Dios es fuerte), 10-IV                     ");
            listDatos.Add("Fabián (hijo de Fabio), 20-I                         ");
            listDatos.Add("Fabio (que cultiva habas), 31-VII                    ");
            listDatos.Add("Fabiola (hija de fabio), 21-III                      ");
            listDatos.Add("Facundo (elocuente), 27-IX                           ");
            listDatos.Add("Faustino (feliz), 15-II                              ");
            listDatos.Add("Fausto (feliz), 6-IX                                 ");
            listDatos.Add("Federico (señor pacífico), 18-VII                    ");
            listDatos.Add("Feliciano (feliz), 24-I                              ");
            listDatos.Add("Felipe (amigo de los caballos), 3-V                  ");
            listDatos.Add("Félix (feliz), 7-I                                   ");
            listDatos.Add("Fermín (firme), 7-VII                                ");
            listDatos.Add("Fernando (Hernando o Hernán, bravo en la paz), 30-V  ");
            listDatos.Add("Fidel (fiel), 24-IV                                  ");
            listDatos.Add("Fortunato (afortunado), 23-IV                        ");
            listDatos.Add("Francisco (frances), 4-X                             ");
            listDatos.Add("Fulgencio (que resplandece), 16-I                    ");
            listDatos.Add("Gabriel (fortaleza de Dios), 19-IX                   ");
            listDatos.Add("Genoveva (de buena estirpe), 3-I                     ");
            listDatos.Add("Gerardo (fuerte con la lanza), 24-IX                 ");
            listDatos.Add("Germán (hermano), 6-IX                               ");
            listDatos.Add("Gertrudis (fuerza de lanza), 17-XI                   ");
            listDatos.Add("Gisela (vara), 7-V                                   ");
            listDatos.Add("Godofredo (paz con Dios), 7-XI                       ");
            listDatos.Add("Gonzalo (luchador en la guerra), 26-I                ");
            listDatos.Add("Gregorio (vigilante), 3-XI                           ");
            listDatos.Add("Guadalupe (rio de lobos), 12-XII                     ");
            listDatos.Add("Guido (guia), 31-III                                 ");
            listDatos.Add("Guillermo (que quiere el yelmo), 10-I                ");
            listDatos.Add("Guzmán (buen hombre), 8-VIII                         ");
            listDatos.Add("Heliodoro (don del sol), 3-VI                        ");
            listDatos.Add("Heraclio (gloria de los héroes), 22-X                ");
            listDatos.Add("Heriberto (distinguido por su ejército), 16-III      ");
            listDatos.Add("Hilarión (alegre), 21-X                              ");
            listDatos.Add("Hildegarda (bastón de combate), 17-IX                ");
            listDatos.Add("Homero (que no ve), 1-XI                             ");
            listDatos.Add("Honorato (honrado), 27-VIII                          ");
            listDatos.Add("Honorio (digno de honor), 30-IX                      ");
            listDatos.Add("Hugo (inteligencia clara), 15-V                      ");
            listDatos.Add("Humberto (destacado gigante), 25-III                 ");
            listDatos.Add("Ifigenia (de mucho linaje), 25-IX                    ");
            listDatos.Add("Ignacio (ardiente), 31-VII                           ");
            listDatos.Add("Ildefonso (o Alfonso, dispuesto al combate), 23-I    ");
            listDatos.Add("Inés (cordera), 21-I                                 ");
            listDatos.Add("Inmaculada (sin mancha), 8-XII                       ");
            listDatos.Add("Inocencio (que no tiene culpa), 22-VI                ");
            listDatos.Add("Irene (paz), 5-IV                                    ");
            listDatos.Add("Ireneo (pacífico), 28-VI                             ");
            listDatos.Add("Isaac (el que se rie), 17-VIII                       ");
            listDatos.Add("Isabel o Elisa (la que jura por Dios), 17-XI         ");
            listDatos.Add("Isaias (salvación de Yahvé), 6-VII                   ");
            listDatos.Add("Ismael (Dios ha oído), 17-VI                         ");
            listDatos.Add("Ivon (Iván o Juan), 19-V                             ");
            listDatos.Add("Jacinto (flor y piedra preciosa), 17-VII             ");
            listDatos.Add("Jacob (Dios protege), 23-VIII                        ");
            listDatos.Add("Jaime (= Santiago), 25-VII                           ");
            listDatos.Add("Javier (casa nueva), 3-XII                           ");
            listDatos.Add("Jeremías (Yahvé levanta), 1-V                        ");
            listDatos.Add("Jerónimo (nombre sagrado), 30-IX                     ");
            listDatos.Add("Jesús (salvación de Yahvé), 1-I                      ");
            listDatos.Add("Joaquím (Yahvé prepara), 26-VII                      ");
            listDatos.Add("Joel (Yahvé es Dios), 13-VII                         ");
            listDatos.Add("Jonás (paloma), 21-VII                               ");
            listDatos.Add("Jorge (agricultor), 23-IV                            ");
            listDatos.Add("Josafat (Yahvé hace justicia), 12-XI                 ");
            listDatos.Add("José (Dios acrecentará), 19-III                      ");
            listDatos.Add("Josué (= Jesús, Salvación de Yahvé), 1-IX            ");
            listDatos.Add("Juan (Dios es misericordia), 24-VI                   ");
            listDatos.Add("Julián (descendiente de Julio), 28-I                 ");
            listDatos.Add("Justino (de Justo), 13-IV                            ");
            listDatos.Add("Juvenal (juvenil), 3-V                               ");
            listDatos.Add("Ladislao (glorioso), 27-VII                          ");
            listDatos.Add("Laura (laurel), 1-VI                                 ");
            listDatos.Add("Laureano (de laurel), 4-VII                          ");
            listDatos.Add("Lázaro (Dios es mi auxilio), 11-II                   ");
            listDatos.Add("Leandro (hombre del pueblo), 13-XI                   ");
            listDatos.Add("Leocadia (¿cuidado del pueblo?), 9-XII               ");
            listDatos.Add("Leonardo (león fuerte), 26-XI                        ");
            listDatos.Add("Leoncio (leonino), 18-VII                            ");
            listDatos.Add("Leonor (Dios es mi luz), 1-VII                       ");
            listDatos.Add("Leopoldo (valiente en el ejército), 15-XI            ");
            listDatos.Add("Lidia (la Lidia), 23-III                             ");
            listDatos.Add("Liduvina (amiga de la gente), 4-IV                   ");
            listDatos.Add("Lino (tejedor de lino), 23-IX                        ");
            listDatos.Add("Lorenzo (de Loreto), 10-VIII                         ");
            listDatos.Add("Lucano (brillante), 30-VIII                          ");
            listDatos.Add("Lucas (luminoso), 18-X                               ");
            listDatos.Add("Lucía (luminosa), 13-XII                             ");
            listDatos.Add("Luciano (brillante), 7-I                             ");
            listDatos.Add("Lucrecia (afortunada), 23-XI                         ");
            listDatos.Add("Luis (= Ludovico, Clodoveo, famoso en la guerra), 21-");
            listDatos.Add("Macario (dichoso), 15-I                              ");
            listDatos.Add("Magdalena (de Magdala), 25-V                         ");
            listDatos.Add("Manuel (Dios con nosotros), 1-I                      ");
            listDatos.Add("Marcelino (= Marcial), 26-IV                         ");
            listDatos.Add("Marcelo (= Marcial), 16-I                            ");
            listDatos.Add("Marcial (dios de la guerra), 30-VI                   ");
            listDatos.Add("Marciano (= Marcial), 6-III                          ");
            listDatos.Add("Marcos (nacido en marzo), 25-IV                      ");
            listDatos.Add("Margarita (perla), 16-XI                             ");
            listDatos.Add("María (excelsa), 18-IX                               ");
            listDatos.Add("Mariano (de María), 17-I                             ");
            listDatos.Add("Marina (del mar), 18-VIII                            ");
            listDatos.Add("Mario (del mar), 19-I                                ");
            listDatos.Add("Marta (atractiva), 29-VII                            ");
            listDatos.Add("Martín (= Marcial), 11-XI                            ");
            listDatos.Add("Mateo (don de Dios), 21-IX                           ");
            listDatos.Add("Matías (don de Dios), 14-V                           ");
            listDatos.Add("Matilde (que lucha con fuerza), 14-III               ");
            listDatos.Add("Mauricio (de Mauritania), 10-VII                     ");
            listDatos.Add("Maximiliano (= Máximo y Emiliano), 29-X              ");
            listDatos.Add("Melchor (rey de la luz), 6-I                         ");
            listDatos.Add("Mercedes (favor), 24-IX                              ");
            listDatos.Add("Miguel (quien como Dios), 29-IX                      ");
            listDatos.Add("Miqueas (quien como Yahvé), 15-I                     ");
            listDatos.Add("Moisés (que saca o salva), 4-IX                      ");
            listDatos.Add("Mónica (monja, solitaria), 27-VIII                   ");
            listDatos.Add("Montserrat (monte aserrado), 27-IV                   ");
            listDatos.Add("Narciso (flor), 18-III                               ");
            listDatos.Add("Natalia (nacida, de Navidad), 27-VII                 ");
            listDatos.Add("Nazario (de Nazaret), 12-I                           ");
            listDatos.Add("Nemesio (justiciero), 25-VIII                        ");
            listDatos.Add("Nicanor (hombre vencedor), 10-I                      ");
            listDatos.Add("Nicodemo (vencedor del pueblo), 3-VIII               ");
            listDatos.Add("Nicolás (vencedor del pueblo), 9-V                   ");
            listDatos.Add("Nicomedes (que piensa en la victoria), 15-IX         ");
            listDatos.Add("Nieves (blanca, pura), 5-VIII                        ");
            listDatos.Add("Noé (descanso), 10-XI                                ");
            listDatos.Add("Norberto (norte claro), 6-VIII                       ");
            listDatos.Add("Octavio (octavo), 20-XI                              ");
            listDatos.Add("Odón (fuerte por su riqueza), 18-XI                  ");
            listDatos.Add("Onésimo (útil), 16-II                                ");
            listDatos.Add("Orestes (montañés), 13-XII                           ");
            listDatos.Add("Oriol (dorado), 1-XI                                 ");
            listDatos.Add("Óscar (dardo de los ases o dioses), 3-II             ");
            listDatos.Add("Oseas (que socorre), 4-VII                           ");
            listDatos.Add("Oswaldo (que tiene el poder de los ases o dioses), 5-");
            listDatos.Add("Otilia (de Oto), 13-XII                              ");
            listDatos.Add("Oto (= Otón = Odón), 2-VII                           ");
            listDatos.Add("Pablo (pequeño), 29-VI                               ");
            listDatos.Add("Pancracio (que todo lo puede), 12-V                  ");
            listDatos.Add("Patricio (noble), 28-IV                              ");
            listDatos.Add("Paula (pequeña), 3-VI                                ");
            listDatos.Add("Pedro (piedra), 29-VI                                ");
            listDatos.Add("Petronila (hija de Pedro), 31-V                      ");
            listDatos.Add("Pío (piadoso), 21-VIII                               ");
            listDatos.Add("Poncio (quinto), 11-V                                ");
            listDatos.Add("Porfirio (purpúreo), 15-IX                           ");
            listDatos.Add("Primo (primero), 9-II                                ");
            listDatos.Add("Priscila (antigua), 8-VII                            ");
            listDatos.Add("Probo (honrado), 15-III                              ");
            listDatos.Add("Rafael (Dios curó), 29-IX                            ");
            listDatos.Add("Raimundo (consejero), 7-I                            ");
            listDatos.Add("Ramiro (consejero), 13-III                           ");
            listDatos.Add("Ramón (= Raimundo), 31-VIII                          ");
            listDatos.Add("Raúl (Rodolfo), 30-XII                               ");
            listDatos.Add("Rebeca (lazo), 1-XI                                  ");
            listDatos.Add("Reinaldo (poderoso por el consejo), 27-IV            ");
            listDatos.Add("Renato (o René, vuelto a nacer), 26-IX               ");
            listDatos.Add("Ricardo (muy rico), 7-II                             ");
            listDatos.Add("Rigoberto (brillante por su riqueza), 12-X           ");
            listDatos.Add("Rita (= Margarita), 22-V                             ");
            listDatos.Add("Roberto (de brillante fama), 17-IX                   ");
            listDatos.Add("Rodrigo (rico en fama), 13-III                       ");
            listDatos.Add("Rogelio (luchador famoso), 16-IX                     ");
            listDatos.Add("Román (= Romano), 3-IV                               ");
            listDatos.Add("Romualdo (lancero famoso), 19-VI                     ");
            listDatos.Add("Roque (elevado), 16-VIII                             ");
            listDatos.Add("Rosalia (rosal), 23-VIII                             ");
            listDatos.Add("Rosario (rosas de la Virgen), 7-X                    ");
            listDatos.Add("Rosendo (que defiende la gloria), 1-III              ");
            listDatos.Add("Rufo (rojo), 27-VIII                                 ");
            listDatos.Add("Ruperto (= Roberto), 27-III                          ");
            listDatos.Add("Salomé (pacífica), 22-X                              ");
            listDatos.Add("Salomón (pacífico), 5-XI                             ");
            listDatos.Add("Salvador (el nombre de Jesús), 6-VIII                ");
            listDatos.Add("Salvio (salvado), 26-VI                              ");
            listDatos.Add("Samuel (el nombre de Dios), 20-VIII                  ");
            listDatos.Add("Sansón (hijo del sol), 27-VI                         ");
            listDatos.Add("Santiago (Sant Yago o Jacobo - Dios protege), 25-VII ");
            listDatos.Add("Sara (princesa), 12-IX                               ");
            listDatos.Add("Sebastián (venerable), 20-I                          ");
            listDatos.Add("Segismundo (que protege con la victoria), 1-V        ");
            listDatos.Add("Sergio (hazañoso), 8-IX                              ");
            listDatos.Add("Severino (severo), 8-I                               ");
            listDatos.Add("Simeón (el que obedece), 8-X                         ");
            listDatos.Add("Simón (chato), 28-X                                  ");
            listDatos.Add("Siro (de Siria), 12-IX                               ");
            listDatos.Add("Sixto (sexto), 3-IV                                  ");
            listDatos.Add("Sofía (sabiduría), 30-IV                             ");
            listDatos.Add("Susana (azucena), 11-VIII                            ");
            listDatos.Add("Tadeo (el que alaba), 28-X                           ");
            listDatos.Add("Tarsicio (de Tarso), 31-I                            ");
            listDatos.Add("Teodora (don de Dios), 7-V                           ");
            listDatos.Add("Teodosia (dada por Dios), 2-IV                       ");
            listDatos.Add("Teófanes (el que manifesta a Dios), 4-XII            ");
            listDatos.Add("Teófila (querida de Dios), 28-XII                    ");
            listDatos.Add("Teresa (o terasia, de la isla de Tera),              ");
            listDatos.Add("Timoteo (que honra a Dios), 26-I                     ");
            listDatos.Add("Tito (seguro, a salvo), 26-I                         ");
            listDatos.Add("Tobías (Dios es bueno), 2-XI                         ");
            listDatos.Add("Tomás (gemelo), 3-VII                                ");
            listDatos.Add("Toribio (tumultuoso), 23-III                         ");
            listDatos.Add("Ubaldo (espíritu audaz), 16-V                        ");
            listDatos.Add("Urbano (de la ciudad), 25-V                          ");
            listDatos.Add("Ursula (osita), 21-X                                 ");
            listDatos.Add("Valentín (fuerte), 14-II                             ");
            listDatos.Add("Valeriano (fuerte), 28-XI                            ");
            listDatos.Add("Velerio (o Valero, fuerte), 29-I                     ");
            listDatos.Add("Venancio (cazador), 13-X                             ");
            listDatos.Add("Verónica (verdadero retrato), 29-VIII                ");
            listDatos.Add("Vicente (el que vence), 5-IV                         ");
            listDatos.Add("Víctor (vencedor), 16-IX                             ");
            listDatos.Add("Victorino (victorioso), 5-IX                         ");
            listDatos.Add("Victorio (victorioso), 30-X                          ");
            listDatos.Add("Vidal (vital), 26-VI                                 ");
            listDatos.Add("Virgilio (que florece), 6-III                        ");
            listDatos.Add("Vladimiro (de gran poder), 1-XI                      ");
            listDatos.Add("Wilfredo (amigo voluntarioso), 9-XII                 ");
            listDatos.Add("Zacarías (Dios recordó), 5-XI                        ");
            listDatos.Add("Zaqueo (puro), 23-VIII                               ");
            return listDatos;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            DB DB = new DB();

            //DB.IniciarConexion();
            
            List<string> lista = Datos();
            txt_localidadCli.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            AutoCompleteStringCollection data = new AutoCompleteStringCollection();
            data.AddRange(lista.ToArray());
            txt_localidadCli.AutoCompleteCustomSource = data;
            txt_localidadCli.AutoCompleteSource = AutoCompleteSource.CustomSource;

        }

        
        
    }
}
